services:
    sftp:
        image: atmoz/sftp
        ports:
            - "22:22"
        volumes:
          - ./sftp:/home
          - ./users.conf:/etc/sftp/users.conf:ro
          - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
          - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key